[package]
name = "pomodoro_todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.190"
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"]}
warp = "0.3.6"
